version: "3.8"

networks:
 localdev:
  name: localdev

services:
 main-api:
  build: WebAPI-Template/
  restart: always
  ports: 
   - "7000:80"
  networks: 
   - localdev
   - redis
  # depends_on: 
  #  - db-server
 

#  db-server:
  # image: microsoft/mssql-server-linux:2017-lastest
  # container_name: db-server
  # environment: 
  #   - ACCEPT_EULA=Y
  #   - MSSQL_SA_PASSWORD=ANPT1234
  #   - MSSQL_TCP_PORT=1433
  # ports: 
  #   - "1400:1433"
  # networks: 
  #   - localdev

 redis:
  image: redis
  container_name: redis
  ports:
  - "6379:6379"
